### ISSUE TITLE
v1.0 Todo List

### ISSUE THREAD

**Issue by NovaSagittarii** [ucrcyber/conway-rts#17]
build tools
- [ ] setup a bundler so protobuf js files and wasm files can actually be used
- [ ] write the rest of the c++ bindings for emscripten

actual development
- [ ] send and decode a vector2 object
- [ ] handle room list, join, leave, etc
- [ ] handle games
