### ISSUE TITLE
Implement Player related things

### ISSUE THREAD

**Issue by NovaSagittarii** [ucrcyber/conway-rts#2]
- [x] #1 

### Tasks
- [x] add header file `include/Player.h`
- [ ] add implementation `src/Player.cpp`
- [ ] add unit tests `tests/Player.cpp`
- [x] add header file `include/Team.h`
- [x] add implementation `src/Team.cpp`
- [ ] add unit tests `tests/Team.cpp`
- [ ] update `CMakeLists.txt` with `src/*.cpp` files
- [ ] update `tests/CMakeLists.txt` with `tests/*.cpp` files

**Comment by NovaSagittarii** [comment]
new uml is out cuz the old one was scuffed

**Comment by NovaSagittarii** [comment]
new uml is out cuz the old one was scuffed
